sudo: false

language: go

go:
  - 1.3
  - 1.3.1
  - 1.3.2
  - 1.3.3
  - 1.4
  - 1.4.1
  - 1.4.2

addons:
  postgresql: "9.4"

env: GOARCH=amd64 TEST_HOST=127.0.0.1 UPPERIO_DB_DEBUG=1

install:
  - sudo apt-get install -y bzr make
  - mkdir -p $GOPATH/src/upper.io
  - mv $PWD $GOPATH/src/upper.io/db
  - cd $GOPATH/src/upper.io/db
  - ls -la
  - go get -v github.com/cznic/ql/ql       # ql command line util.
  - go get -v -t -d
  - go get -v -t -d upper.io/db/mysql
  - go get -v -t -d upper.io/db/sqlite
  - go get -v -t -d upper.io/db/postgresql
  - go get -v -t -d upper.io/db/mongo
  - go get -v -t -d upper.io/db/ql
  - go get -v github.com/jmoiron/sqlx
  - (cd $GOPATH/src/github.com/jmoiron/sqlx && git pull -a && git checkout ptrs) # temporal fix
  - (cd $GOPATH/src/github.com/jmoiron/sqlx && go build -a && go install)
  - export TRAVIS_BUILD_DIR=$GOPATH/src/upper.io/db

services:
  - mongodb

before_script:
  - mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql

  - mongo upperio_tests --eval 'db.addUser("upperio_tests", "upperio_secret")'

  - (cd mysql/_dumps && make)
  - (cd postgresql/_dumps && make)
  - (cd sqlite/_dumps && make)
  - (cd ql/_dumps && make)

  - cat ql/_dumps/structs.sql | $GOPATH/bin/ql -db ql/_dumps/test.db

script:
  - cd $GOPATH/src/upper.io/db
  - go test upper.io/db/mysql -test.bench=.
  - go test upper.io/db/sqlite -test.bench=.
  - go test upper.io/db/ql -test.bench=.
  - go test upper.io/db/mongo -test.bench=.
  - go test -test.v
