language: go

go:
#  - 1.1 // Unsupported, QL fails to compile on go < 1.2.
#  - 1.2 // Unsupported on travis because it fails to fetch some resources via HTTPs.
#  - 1.2.1
#  - 1.2.2
  - 1.3
  - 1.3.1
  - 1.3.2
  - 1.3.3
  - 1.4
  - 1.4.1
  - 1.4.2

env: GOARCH=amd64 TEST_HOST=127.0.0.1 UPPERIO_DB_DEBUG=1

install:
  - sudo apt-get install -y bzr make
  - mkdir -p $GOPATH/src/upper.io/v2
  - mv $PWD $GOPATH/src/upper.io/v2/db
  - cd $GOPATH/src/upper.io/v2/db
  - ls -la
  - go get -v github.com/cznic/ql/ql       # ql command line util.
  - go get -v -t -d
  - go get -v -t -d upper.io/v2/db/mysql
  - go get -v -t -d upper.io/v2/db/sqlite
  - go get -v -t -d upper.io/v2/db/postgresql
  - go get -v -t -d upper.io/v2/db/mongo
  - go get -v -t -d upper.io/v2/db/ql
  - export TRAVIS_BUILD_DIR=$GOPATH/src/upper.io/v2/db

services:
  - mongodb

before_script:
  - mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql
  - cat mysql/_dumps/setup.sql | mysql -uroot
  - cat mysql/_dumps/structs.sql | mysql -uupperio -pupperio upperio_tests

  - cat postgresql/_dumps/setup.sql | psql -U postgres
  - cat postgresql/_dumps/structs.sql | PGPASSWORD="upperio" psql -U upperio upperio_tests

  - mongo upperio_tests --eval 'db.addUser("upperio", "upperio")'

  - (cd mysql/_dumps && make)
  - (cd postgresql/_dumps && make)
  - (cd sqlite/_dumps && make)
  - (cd ql/_dumps && make)

  - cat ql/_dumps/structs.sql | $GOPATH/bin/ql -db ql/_dumps/test.db

script:
  - (cd $GOPATH/src/github.com/jmoiron/sqlx && git pull -a && git checkout ptrs && go build -a && go install) # Peter's branch.
  - cd $GOPATH/src/upper.io/v2/db
  - go test upper.io/v2/db/mysql -test.bench=.
  - go test upper.io/v2/db/sqlite -test.bench=.
  - go test upper.io/v2/db/ql -test.bench=.
  - go test upper.io/v2/db/mongo -test.bench=.
  - go test -test.v
